### ISSUE TITLE
Pure ascii

### ISSUE THREAD

**Issue by aslakr** [nkizz/mop3#9] opened 2023-06-26 13:03 UTC
Some clients doesn't support unicode well, or at least only partly.

Initially I tought that conversion to [ISO-8859-1 (Latin 1)](https://en.wikipedia.org/wiki/ISO/IEC_8859-1 "ISO/IEC 8859-1 on Wikipedia") or  [ISO-8859-15](https://en.wikipedia.org/wiki/ISO/IEC_8859-15 "ISO/IEC 8859-15 on Wikipedia") etc. might work, but then I noticed that a lot of post now contains `’` (for things like `I’m`) instead of `'`. And then there are emojis. 

So maybe `--ascii` should use something like <https://github.com/anyascii/anyascii#rust> (and have the option `--unicode` keeping the original unicode)?

**Comment by miakizz** [comment] 2023-06-26 13:22
Does the current --ascii not work well with your client? I just made a change to it, so a regression may have occured

**Comment by aslakr** [comment] 2023-06-27 14:29
It's not directly related to nkizz/mop3#4

It's more that som clients doesn't support Unicode, or only support Unicode as definded some time ago (i.e. no emojis). I suspect debugging might also be easier when it's possible to convert to pure ascii.

![Screenshot of MacSOUP 2.4.6 on Mac OS 9.2. MacSOUP 2.4.6 is not capable to decode UTF-8](https://github.com/nkizz/mop3/assets/80737/ac2502dd-a1b0-4f3a-870b-92fd3a9aa661 "Screenshot of MacSOUP 2.4.6 on Mac OS 9.2.")

**Comment by miakizz** [comment] 2023-06-27 14:33
That is exactly what the --ascii flag should do, are you using that? because if you are, it shouldn't be sending any non-ascii characters

**Comment by aslakr** [comment] 2023-06-27 15:06
Ah, I see now that `deunicode` should do the same. 

But it doesn't seem to be any difference between using ``--ascii`` and not.

For example  https://hachyderm.io/@mekkaokereke/110616400584796373

become:

```mbox
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

"Be kind" is not a complete thought. Be kind to who? And don't say "Be kind =
to
everyone!=F0=9F=A4=97" Because it's not possible to be kind to everyone.

Mr. Rogers is often held up as the example of someone that was kind to
everyone. But even he roasted racists! He was unsympathetic to bigots who
wanted to hold on to America's tradition of segregation. Something, somethin=
g,
paradox of tolerance.

"Be kind" is often the coward's way out of speaking up for those that need
defending.

[https://m.youtube.com/watch?v=3DK6O_Ep9bY0U&t=3D1m30s][1]

[1]: https://m.youtube.com/watch?v=3DK6O_Ep9bY0U&t=3D1m30s

https://hachyderm.io/@mekkaokereke/110616400584796373
```

when using:

```sh
mop3 --account "aslakr@mastodon.social" --token "…" --pop3port 1100 --url --ascii  --nosmtp 
```

**Comment by miakizz** [comment] 2023-11-14 15:21
This is a bit of a necropost, but I thought I'd put an explanation here for future reference.
This is a regression from switching from assembling the emails manually to using a library. The library was outsmarting me and escaping utf-8 to make it 7-bit clean. This means there wasn't actually any unicode in the email to deunicode, since it had already been escaped. It now adapts the text before passing it to the library, which transforms it correctly.
The messages still report the charset as utf-8, but my guess is that a client will either ignore that header, or respect it and handle the ascii correctly. The fix will be committed soon

Thanks for the report!

**Closed as completed by miakizz** 2023-11-14 15:21 UTC
