### ISSUE TITLE
thread 'main' panicked at 'Server sent malformed JSON ...'

### ISSUE THREAD

**Issue by aslakr** [nkizz/mop3#4] opened 2023-05-11 14:42 UTC
mop3 seems to panick: 

```sh
RUST_BACKTRACE=full mop3-macos-arm64 --account "...@mastodon.social" \
  --token "..." \
  --pop3port 10110 \
  --ascii --nosmtp
```

result in the following when pop3 client tries to connect:

```console
Listening on ("127.0.0.1", 10110)
thread 'main' panicked at 'Server sent malformed JSON: Error("expected `,` or `}`", line: 1, column: 9869)', src/main.rs:231:45
stack backtrace:
   0:        0x103017794 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb33e6e8152f78c95
   1:        0x10302ffec - core::fmt::write::hd33da007f7a27e39
   2:        0x103012b94 - std::io::Write::write_fmt::h7edc10723862001e
   3:        0x1030175a8 - std::sys_common::backtrace::print::h895ee35b3f17b334
   4:        0x103018d1c - std::panicking::default_hook::{{closure}}::h3b7ee083edc2ea3e
   5:        0x103018a74 - std::panicking::default_hook::h4e7c2c28eba716f5
   6:        0x103019340 - std::panicking::rust_panic_with_hook::h1672176227032c45
   7:        0x103019160 - std::panicking::begin_panic_handler::{{closure}}::h0b2d072f9624d32e
   8:        0x103017bfc - std::sys_common::backtrace::__rust_end_short_backtrace::he9abda779115b93c
   9:        0x103018ebc - _rust_begin_unwind
  10:        0x103044654 - core::panicking::panic_fmt::h23ae44661fec0889
  11:        0x103044974 - core::result::unwrap_failed::h414a6cbb12b1e143
  12:        0x102d5c6e8 - mop3::handle_pop_connection::h1edde0d9242564ed
  13:        0x102d5892c - mop3::main::h3c3a97baba12433a
  14:        0x102d32678 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0d27018abf24d9ca
  15:        0x102d32834 - std::rt::lang_start::{{closure}}::h966e38f1108142fc
  16:        0x10300ea00 - std::rt::lang_start_internal::h00a235e820a7f01c
  17:        0x102d63e1c - _main
```

**Comment by miakizz** [comment] 2023-05-13 17:39
Looks like your instance is sending something that the JSON parser is disagreeing with. If you're still getting the error, HEAD currently has a debug flag. Save the JSON it prints out, and I can take a look (you can trim it to the problematic portion)

**Comment by aslakr** [comment] 2023-05-15 09:21
Running 

```sh
./mop3 --account "...@bsd.network" \
  --token "..." \
  --pop3port 1100 \
  --ascii --nosmtp \
  --debug > mop3-debug-out-$(date -Iminutes).txt 2> mop3-debug-err-$(date -Iminutes).txt
```

and using https://github.com/nicm/fdm as a pop3 client result in: 

- [mop3-debug-err-2023-05-15T10:03+02:00.txt](https://github.com/nkizz/mop3/files/11475720/mop3-debug-err-2023-05-15T10.03%2B02.00.txt)
- [mop3-debug-out-2023-05-15T10:03+02:00.txt](https://github.com/nkizz/mop3/files/11475721/mop3-debug-out-2023-05-15T10.03%2B02.00.txt) (note `Listening on ("127.0.0.1", 1100)` on the first line.


`jq` doesn't seem to complain when using:

```sh
tail -n +2 mop3-debug-out-2023-05-15T10:03+02:00.txt | jq
```

**Comment by LionsPhil** [comment] 2023-06-15 23:40
I'm pretty sure this is a logic error with `--ascii`, and I can repro this problem with it (my feed is full of various unicode abuses---the particular trigger seemed to be this DaShareZone toot containing ironic smart quotes in the image description: https://mas.to/@dasharez0ne/110549663899399880 ), and work around it by removing it.

[src/main.rs:233](https://github.com/nkizz/mop3/blob/d5e9a73efe3665c4eb71c0266da5e9c3deb75eb8/src/main.rs#L233) (just before the crashing parse) calls `deunicode` *before* attempting to parse the JSON, but taking a reasonable guess at what that library does with smart quotes, it's dropping unescaped regular quotes in the middle of JSON strings, with hilarious results. This probably needs reworking to first parse the JSON and *then* deunicode each individual string you're going to pass onward to the POP3 client.

(...but I haven't tested this, not least because I've spent hours fighting legacy POP3 clients by this point and it's almost 1am).

**Comment by miakizz** [comment] 2023-06-22 21:37
To be honest, I completely thought it already performed the conversion after parsing, but you're totally right. I didn't reproduce the problem, but since both your and @aslakr's crashes contains smart quotes, I'm guessing that's the issue. Fixed in https://github.com/nkizz/mop3/commit/d56d31b206ff6dff6cddfcb05309a393ce94869b, let me know if it pops up again. Thanks for the investigation!

**Closed as completed by miakizz** 2023-06-22 21:37 UTC
